# Generated by Django 6.0 on 2026-02-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmvalidation',
            name='sector_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
