# Generated by Django 6.0 on 2025-12-19 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('delete_field', models.CharField(default='no', max_length=10)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='projectstafftbl',
            name='farms',
        ),
        migrations.RemoveField(
            model_name='rehabassistantstbl',
            name='districtTbl_foreignkey',
        ),
        migrations.AlterField(
            model_name='maintenancereport',
            name='Please_Sign_Here',
            field=models.ImageField(blank=True, null=True, upload_to='signature/2025-12-19'),
        ),
        migrations.AlterField(
            model_name='mobilemaintenance',
            name='current_farm_pic',
            field=models.ImageField(blank=True, null=True, upload_to='obweeklymonitoring/2025-12-19'),
        ),
        migrations.AlterField(
            model_name='verificationworkdone',
            name='current_farm_pic',
            field=models.ImageField(blank=True, null=True, upload_to='verificationworkdone/2025-12-19'),
        ),
        migrations.AlterField(
            model_name='weeklymontoringtbl',
            name='current_farm_pic',
            field=models.ImageField(blank=True, null=True, upload_to='weeklymonitoring/2025-12-19'),
        ),
        migrations.AddField(
            model_name='projectstafftbl',
            name='projectTbl_foreignkey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.projecttbl'),
        ),
        migrations.AddField(
            model_name='rehabassistantstbl',
            name='projectTbl_foreignkey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.projecttbl'),
        ),
    ]
