# Generated by Django 6.0 on 2026-01-29 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('portal', '0002_projecttbl_remove_projectstafftbl_farms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Configuration', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('show_icons', models.BooleanField(default=True)),
                ('expand_all', models.BooleanField(default=False, help_text='Expand all menu items by default')),
                ('show_user_info', models.BooleanField(default=True, help_text='Show user info in sidebar')),
                ('show_search', models.BooleanField(default=False, help_text='Show search in sidebar')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto (System)')], default='light', max_length=20)),
            ],
            options={
                'verbose_name': 'Sidebar Configuration',
                'verbose_name_plural': 'Sidebar Configurations',
            },
        ),
        migrations.AlterField(
            model_name='maintenancereport',
            name='Please_Sign_Here',
            field=models.ImageField(blank=True, null=True, upload_to='signature/2026-01-29'),
        ),
        migrations.AlterField(
            model_name='mobilemaintenance',
            name='current_farm_pic',
            field=models.ImageField(blank=True, null=True, upload_to='obweeklymonitoring/2026-01-29'),
        ),
        migrations.AlterField(
            model_name='verificationworkdone',
            name='current_farm_pic',
            field=models.ImageField(blank=True, null=True, upload_to='verificationworkdone/2026-01-29'),
        ),
        migrations.AlterField(
            model_name='weeklymontoringtbl',
            name='current_farm_pic',
            field=models.ImageField(blank=True, null=True, upload_to='weeklymonitoring/2026-01-29'),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text="FontAwesome icon class (e.g., 'fas fa-chart-pie')", max_length=50)),
                ('url', models.CharField(blank=True, help_text="URL pattern (e.g., '/dashboard/')", max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_groups', models.ManyToManyField(blank=True, help_text='User groups that can access this menu item', related_name='menu_items', to='auth.group')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='FontAwesome icon class', max_length=50)),
                ('url', models.CharField(blank=True, help_text='URL pattern', max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_groups', models.ManyToManyField(blank=True, help_text='User groups that can access this sub-menu item', related_name='sub_menu_items', to='auth.group')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='portal.menuitem')),
            ],
            options={
                'verbose_name': 'Sub Menu Item',
                'verbose_name_plural': 'Sub Menu Items',
                'ordering': ['parent__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NestedMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='FontAwesome icon class', max_length=50)),
                ('url', models.CharField(help_text='URL pattern', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_groups', models.ManyToManyField(blank=True, help_text='User groups that can access this nested menu item', related_name='nested_menu_items', to='auth.group')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nested_items', to='portal.submenuitem')),
            ],
            options={
                'verbose_name': 'Nested Menu Item',
                'verbose_name_plural': 'Nested Menu Items',
                'ordering': ['parent__parent__order', 'parent__order', 'order', 'name'],
            },
        ),
    ]
