# Generated by Django 6.0 on 2026-02-11 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_farmvalidation_sector_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityReportingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('delete_field', models.CharField(default='no', max_length=10)),
                ('uid', models.CharField(blank=True, max_length=2500, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('reporting_date', models.DateField(blank=True, null=True)),
                ('no_rehab_assistants', models.IntegerField(blank=True, default=0, null=True)),
                ('area_covered_ha', models.FloatField(blank=True, default=0.0, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('farm_ref_number', models.CharField(blank=True, max_length=250, null=True)),
                ('farm_size_ha', models.FloatField(blank=True, default=0.0, null=True)),
                ('number_of_people_in_group', models.IntegerField(blank=True, default=0, null=True)),
                ('group_work', models.CharField(blank=True, max_length=50, null=True)),
                ('sector', models.IntegerField(blank=True, null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_activities_reporting', to='portal.activities')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.stafftbl')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.community')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.cocoadistrict')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.farmdetailstbl')),
                ('main_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_activities_reporting', to='portal.activities')),
                ('projectTbl_foreignkey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.projecttbl')),
                ('ras', models.ManyToManyField(blank=True, to='portal.personnelmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
