# Generated by Django 6.0 on 2026-01-29 16:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('portal', '0003_sidebarconfiguration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AlterModelOptions(
            name='submenuitem',
            options={'ordering': ['order', 'display_name'], 'verbose_name': 'Sub Menu Item', 'verbose_name_plural': 'Sub Menu Items'},
        ),
        migrations.RemoveField(
            model_name='submenuitem',
            name='parent',
        ),
        migrations.AddField(
            model_name='submenuitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submenuitem',
            name='parent_menu',
            field=models.ForeignKey(blank=True, help_text='Parent menu item (leave blank if parent is another sub-item)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='portal.menuitem'),
        ),
        migrations.AddField(
            model_name='submenuitem',
            name='parent_submenu',
            field=models.ForeignKey(blank=True, help_text='Parent sub-menu item (for nested structure)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='portal.submenuitem'),
        ),
        migrations.AddField(
            model_name='submenuitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='icon',
            field=models.CharField(help_text='FontAwesome icon class', max_length=50),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, help_text='URL pattern', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='submenuitem',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='User groups that can access this menu item', related_name='sub_menu_items', to='auth.group'),
        ),
        migrations.DeleteModel(
            name='NestedMenuItem',
        ),
    ]
