# Generated by Django 6.0 on 2026-02-11 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_activityreportingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='QR_CodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('delete_field', models.CharField(default='no', max_length=10)),
                ('uid', models.CharField(blank=True, max_length=2500, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='growthmonitoringmodel',
            name='qr_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.qr_codemodel'),
        ),
    ]
