# Generated by Django 6.0 on 2026-01-29 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_menuitem_options_alter_submenuitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['order', 'display_name'], 'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent menu item (leave blank for top-level menu)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='portal.menuitem'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='icon',
            field=models.CharField(help_text="FontAwesome icon class (e.g., 'fas fa-chart-pie')", max_length=50),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, help_text="URL pattern (e.g., '/dashboard/')", max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='SubMenuItem',
        ),
    ]
