# Generated by Django 6.0 on 2026-02-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_qr_codemodel_growthmonitoringmodel_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_codemodel',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR code image file', null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='qr_codemodel',
            name='uid',
            field=models.CharField(blank=True, db_index=True, max_length=2500, null=True),
        ),
    ]
