# Generated by Django 6.0 on 2026-02-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_menuitem_options_menuitem_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancereport',
            name='Please_Sign_Here',
            field=models.ImageField(blank=True, null=True, upload_to='signature/2026-02-02'),
        ),
        migrations.AlterField(
            model_name='mobilemaintenance',
            name='current_farm_pic',
            field=models.ImageField(blank=True, null=True, upload_to='obweeklymonitoring/2026-02-02'),
        ),
        migrations.AlterField(
            model_name='verificationworkdone',
            name='current_farm_pic',
            field=models.ImageField(blank=True, null=True, upload_to='verificationworkdone/2026-02-02'),
        ),
        migrations.AlterField(
            model_name='weeklymontoringtbl',
            name='current_farm_pic',
            field=models.ImageField(blank=True, null=True, upload_to='weeklymonitoring/2026-02-02'),
        ),
    ]
