# Generated by Django 6.0 on 2026-02-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_qr_codemodel_qr_code_alter_qr_codemodel_uid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnelassignmentmodel',
            options={'verbose_name': 'Rehab Assistant', 'verbose_name_plural': 'Rehab Assistants'},
        ),
        migrations.AddField(
            model_name='personnelmodel',
            name='SSNIT_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personnelmodel',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personnelmodel',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personnelmodel',
            name='belongs_to_ra',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='personnelmodel',
            name='momo_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
