# Generated by Django 6.0 on 2026-02-11 16:55

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_personnelassignmentmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('delete_field', models.CharField(default='no', max_length=10)),
                ('equipment_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date_of_capturing', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Under Repair', 'Under Repair')], default='Good', max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(max_length=250)),
                ('pic_serial_number', models.ImageField(blank=True, null=True, upload_to='equipment/serial/')),
                ('pic_equipment', models.ImageField(blank=True, null=True, upload_to='equipment/device/')),
                ('uid', models.CharField(blank=True, max_length=2500, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.cocoadistrict')),
                ('projectTbl_foreignkey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.projecttbl')),
                ('staff_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.stafftbl')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentAssignmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('delete_field', models.CharField(default='no', max_length=10)),
                ('assignment_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('condition_at_assignment', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Assigned', max_length=50)),
                ('uid', models.CharField(blank=True, max_length=2500, null=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_assignments', to='portal.stafftbl')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.stafftbl')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.cocoadistrict')),
                ('projectTbl_foreignkey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.projecttbl')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.equipmentmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutbreakFarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('delete_field', models.CharField(default='no', max_length=10)),
                ('outbreak_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('farm_location', models.CharField(max_length=250)),
                ('farmer_name', models.CharField(max_length=250)),
                ('farmer_age', models.IntegerField(blank=True, null=True)),
                ('id_type', models.CharField(blank=True, max_length=50, null=True)),
                ('id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('farmer_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('cocoa_type', models.CharField(blank=True, max_length=100, null=True)),
                ('age_class', models.CharField(blank=True, max_length=50, null=True)),
                ('farm_area', models.FloatField()),
                ('communitytbl', models.CharField(blank=True, max_length=250, null=True)),
                ('inspection_date', models.DateField()),
                ('temp_code', models.CharField(blank=True, max_length=100, null=True)),
                ('disease_type', models.CharField(max_length=250)),
                ('date_reported', models.DateField()),
                ('status', models.IntegerField(default=0)),
                ('coordinates', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=50)),
                ('treatment_applied', models.TextField(blank=True, null=True)),
                ('treatment_date', models.DateField(blank=True, null=True)),
                ('uid', models.CharField(blank=True, max_length=2500, null=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.community')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.cocoadistrict')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.farmdetailstbl')),
                ('projectTbl_foreignkey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.projecttbl')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.region')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.stafftbl')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
