# Generated by Django 6.0 on 2026-02-02 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_maintenancereport_please_sign_here_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreport',
            name='projectTbl_foreignkey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.projecttbl'),
        ),
    ]
