# Generated by Django 6.0 on 2026-02-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_equipmentmodel_equipmentassignmentmodel_outbreakfarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelmodel',
            name='staff_id',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
