# Generated by Django 6.0 on 2026-02-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_paymentreport_projecttbl_foreignkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreport',
            name='project',
            field=models.CharField(blank=True, max_length=2540, null=True),
        ),
    ]
