# Generated by Django 6.0 on 2026-02-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_personnelmodel_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
    ]
