# Generated by Django 6.0 on 2026-02-02 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_paymentreport_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetailedreport',
            name='districtTbl_foreignkey',
        ),
        migrations.AddField(
            model_name='paymentdetailedreport',
            name='projectTbl_foreignkey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.projecttbl'),
        ),
    ]
