# Generated by Django 6.0 on 2026-02-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_remove_paymentdetailedreport_districttbl_foreignkey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetailedreport',
            name='project',
            field=models.CharField(blank=True, max_length=2540, null=True),
        ),
    ]
