# Generated by Django 6.0 on 2026-02-17 08:16

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_personnelmodel_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='qr_codemodel',
            managers=[
                ('default_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='month',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='week',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='year',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='posroutemonitoring',
            name='staffTbl_foreignkey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.personnelmodel'),
        ),
    ]
