# Generated by Django 6.0 on 2026-02-02 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_paymentdetailedreport_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='project',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='projectStaffTbl_foreignkey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.projectstafftbl'),
        ),
    ]
