# Generated by Django 6.0 on 2026-02-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_alter_qr_codemodel_managers_feedback_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='sub_activity',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
