# Generated by Django 6.0 on 2026-02-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_alter_activities_sub_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreportingmodel',
            name='sub_activities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyreportingmodel',
            name='sub_activities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
