# Generated by Django 6.0 on 2026-02-23 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_activityreportingmodel_sub_activities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreportingmodel',
            name='contractor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.contractorstbl'),
        ),
        migrations.AddField(
            model_name='activityreportingmodel',
            name='is_done_by_contractor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activityreportingmodel',
            name='is_done_equally',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activityreportingmodel',
            name='rounds_of_weeding',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dailyreportingmodel',
            name='contractor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.contractorstbl'),
        ),
        migrations.AddField(
            model_name='dailyreportingmodel',
            name='is_done_by_contractor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyreportingmodel',
            name='is_done_equally',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyreportingmodel',
            name='rounds_of_weeding',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
