# Generated by Django 6.0 on 2026-03-09 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_activityreportingmodel_contractor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='activities',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='activityreportingmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_reporting_created_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='activityreportingmodel',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_reporting_modified_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='calculatedarea',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculated_area_created_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='calculatedarea',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculated_area_modified_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='contractorcertificatemodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_certificate_created_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='contractorcertificatemodel',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_certificate_modified_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='contractorcertificateverificationmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_certificate_verification_created_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='contractorcertificateverificationmodel',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_certificate_verification_modified_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='contractorstbl',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractors_created_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='contractorstbl',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractors_modified_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='contratordistrictassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_assignments_created_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='contratordistrictassignment',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_assignments_modified_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='dailyreportingmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_reporting_created_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='dailyreportingmodel',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_reporting_modified_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='detailedpaymentreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detailed_payment_report_created_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='detailedpaymentreport',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detailed_payment_report_modified_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='equipmentassignmentmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_assignment_created_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='equipmentassignmentmodel',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_assignment_modified_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='equipmentmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_created_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='equipmentmodel',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_modified_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='farmdetailstbl',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmsdetails_created_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='farmdetailstbl',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmsdetails_modified_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='farms',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farms_created_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='farms',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farms_modified_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='farmvalidation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farm_validation_created_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='farmvalidation',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farm_validation_modified_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_created_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_modified_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='growthmonitoringmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='growth_monitoring_created_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='growthmonitoringmodel',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='growth_monitoring_modified_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='irrigationmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_created_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='irrigationmodel',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_modified_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='issuemodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_created_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='issuemodel',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_modified_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joborder_created_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joborder_modified_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='mappedfarms',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapped_farms_created_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='mappedfarms',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapped_farms_modified_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='outbreakfarm',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbreak_farm_created_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='outbreakfarm',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbreak_farm_modified_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='outbreakfarmmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbreak_farm_model_created_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='outbreakfarmmodel',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbreak_farm_model_modified_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='paymentreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_report_created_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='paymentreport',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_report_modified_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='personnelassignmentmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnel_assignment_created_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='personnelassignmentmodel',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnel_assignment_modified_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='personnelmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnel_created_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='personnelmodel',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnel_modified_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='posroutemonitoring',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos_routemonitoring_created_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='posroutemonitoring',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos_routemonitoring_modified_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='qr_codemodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_code_created_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='qr_codemodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qr_codemodel',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qr_codemodel',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_code_modified_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='verifyrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verify_created_by', to='portal.stafftbl'),
        ),
        migrations.AddField(
            model_name='verifyrecord',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verify_modified_by', to='portal.stafftbl'),
        ),
    ]
