# Generated by Django 6.0 on 2026-03-09 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_activities_created_by_activities_modified_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='irrigationTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('delete_field', models.CharField(default='no', max_length=10)),
                ('irrigation_type', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_type_created_by', to='portal.stafftbl')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_type_modified_by', to='portal.stafftbl')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='irrigationmodel',
            name='irrigation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.irrigationtypemodel'),
        ),
    ]
