# Generated by Django 6.0 on 2026-03-11 11:59

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_irrigationtypemodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=255, unique=True)),
                ('size_Ha', models.FloatField(blank=True, null=True)),
                ('mean_pH', models.FloatField(blank=True, null=True)),
                ('mean_OC', models.FloatField(blank=True, null=True)),
                ('Texture_co', models.CharField(blank=True, max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sector_created_by', to='portal.stafftbl')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sector_modified_by', to='portal.stafftbl')),
            ],
        ),
        migrations.AddField(
            model_name='farmdetailstbl',
            name='sector_foreignkey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.sectormodel'),
        ),
        migrations.AddField(
            model_name='farmvalidation',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.sectormodel'),
        ),
        migrations.AddField(
            model_name='irrigationmodel',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.sectormodel'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='sector_foreignkey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.sectormodel'),
        ),
        migrations.AddField(
            model_name='outbreakfarm',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.sectormodel'),
        ),
        migrations.AddField(
            model_name='verifyrecord',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.sectormodel'),
        ),
    ]
