# Generated by Django 6.0 on 2026-03-11 12:16

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_sectormodel_farmdetailstbl_sector_foreignkey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectormodel',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, dim=3, null=True, srid=4326),
        ),
        migrations.AlterModelTable(
            name='sectormodel',
            table='portal_sectormodel',
        ),
    ]
