# Generated by Django 6.0 on 2026-03-11 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_alter_sectormodel_geom_alter_sectormodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sectormodel',
            table=None,
        ),
    ]
