# Generated by Django 6.0 on 2026-03-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_alter_sectormodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectormodel',
            name='Texture_co',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
