# Generated by Django 6.0 on 2026-03-11 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_alter_sectormodel_texture_co'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreportingmodel',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.sectormodel'),
        ),
    ]
