# Generated by Django 6.0 on 2026-03-11 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_alter_activityreportingmodel_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreportingmodel',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.sectormodel'),
        ),
    ]
