# Generated by Django 6.0 on 2025-12-17 17:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('device_name', models.CharField(max_length=200)),
                ('device_type', models.CharField(choices=[('soil', 'Soil Moisture Sensor'), ('temperature', 'Temperature Sensor'), ('humidity', 'Humidity Sensor'), ('multi', 'Multi-Sensor Device')], default='multi', max_length=50)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('api_key', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperature', models.FloatField(blank=True, help_text='Temperature in Celsius', null=True)),
                ('humidity', models.FloatField(blank=True, help_text='Humidity percentage', null=True)),
                ('soil_moisture', models.FloatField(blank=True, help_text='Soil moisture percentage', null=True)),
                ('soil_raw', models.IntegerField(blank=True, help_text='Raw analog soil sensor value (0-4095)', null=True)),
                ('battery_level', models.FloatField(blank=True, help_text='Battery level percentage', null=True)),
                ('signal_strength', models.IntegerField(blank=True, help_text='Signal strength', null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.device')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='sensors_sen_timesta_557074_idx'), models.Index(fields=['device', '-timestamp'], name='sensors_sen_device__b6d36a_idx')],
            },
        ),
    ]
