"""
Django settings for farm_management project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config
from import_export.formats.base_formats import CSV, XLSX, XLS, JSON

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-))1+s(qbm54duuc)=c**28xy)9h98r(8%bul7*n&agwr#sik0t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Add this to settings.py
SITE_ID = 1


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    "channels",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
     'django.contrib.gis',

    'core',
    'portal',
    "sensors",
    "API",
    'sidebar',

    'import_export',
    'dbbackup',
    'leaflet',
    'leaflet_admin_list',
    'drf_yasg',
    'storages',
    'crispy_forms',
    "crispy_bootstrap4",
    'django.contrib.humanize',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
]



# Optional: Configure Leaflet
LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (5.678, -1.234),  # Ghana coordinates
    'DEFAULT_ZOOM': 6,
    'MIN_ZOOM': 5,
    'MAX_ZOOM': 28,
    'MIN_CENTER': (5.678, -1.234),
    'MAX_CENTER': (5.678, -1.234),
    'DEFAULT_PRECISION': 6,
    'CRS': 'EPSG:4326',
    'SPATIAL_EXTENT': (-180, -90, 180, 90),
    'SPATIAL_EXTENT_CRS': 'EPSG:4326',
    'DEFAULT_TILE_LAYER': 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
    'DEFAULT_TILE_LAYER_ATTRIBUTION': '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
    
    'RESET_VIEW': False,
    'SCALE': 'both',
    'ATTRIBUTION_PREFIX': 'Powered by django-leaflet',
}

# GDAL configuration for Ubuntu/Debian
if os.name == 'posix':  # Linux
    # Common GDAL library paths on Ubuntu/Debian
    possible_paths = [
        '/usr/lib/x86_64-linux-gnu/libgdal.so',
        '/usr/lib/x86_64-linux-gnu/libgdal.so.32',  # GDAL 3.2
        '/usr/lib/x86_64-linux-gnu/libgdal.so.34',  # GDAL 3.4
        '/usr/lib/x86_64-linux-gnu/libgdal.so.36',  # GDAL 3.6
        '/usr/lib/libgdal.so',
        '/usr/lib/x86_64-linux-gnu/ogdi/4.1/libgdal.so',
        '/usr/lib/x86_64-linux-gnu/libgdal.so.34.3.8.4',
        '/usr/lib/x86_64-linux-gnu/libgdal.so.34',
        '/usr/lib/x86_64-linux-gnu/libgdal.so'
    ]
    
    for path in possible_paths:
        if os.path.exists(path):
            GDAL_LIBRARY_PATH = path
            print(f"Found GDAL at: {path}")
            break
    else:
        GDAL_LIBRARY_PATH = ''
        print("GDAL library not found")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    
    'whitenoise.middleware.WhiteNoiseMiddleware',
    
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    
    
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    
    
]



JAZZMIN_SETTINGS = {
    # Site identification (uncomment if needed)
    # "site_title": "AmpPortal Admin",
    # "site_header": "AmpPortal Admin Dashboard", 
    # "site_brand": "AMP LOGISTICS",
    # "welcome_sign": "Welcome to AmpPortal Admin",
    # "copyright": "AmpPortal © 2025",
    
    # Sidebar configuration
    "show_sidebar": True,
    "navigation_expanded": False,  # This makes sidebar collapsed by default
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["auth", "your_app_name", "another_app"],
    
    # Enable UI builder for testing
    "show_ui_builder": True,

    # Icons configuration
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user", 
        "auth.group": "fas fa-users",
        "your_app.ModelName": "fas fa-boxes",
    },

    # Top menu configuration
    "topmenu_links": [
        # Link to homepage
        {"name": "Home", "url": "/", "permissions": ["auth.view_user"], "new_window": False},

        # Direct model links
        {"model": "auth.User"},
        {"model": "auth.Group"},
        {"model": "admin.LogEntry"},

        # Link to a named Django URL (using reverse())
        {"name": "Dashboard", "url_name": "dashboard", "permissions": ["dashboard.view_dashboard"]},
        
        # Custom API buttons
        {"name": "Generate Farmer Quotas", "url": "generate-farmer-quotas", "permissions": ["auth.view_user"], "new_window": False},
        {"name": "Generate Society Limit", "url": "generate-society-limit", "permissions": ["auth.view_user"], "new_window": False},
    ],

    # User menu configuration  
    "usermenu_links": [
        {"name": "Support", "url": "https://support.example.com", "new_window": True},
    ],
}

#Nananom
JAZZMIN_UI_TWEAKS = {
    # Text size settings
    "navbar_small_text": True,
    "footer_small_text": True, 
    "body_small_text": True,
    "brand_small_text": False,
    
    # Color scheme
    "brand_colour": "navbar-success",
    "accent": "accent-success",
    "navbar": "navbar-success navbar-dark",
    
    # Layout settings
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,  # Important for sidebar behavior
    
    # Sidebar settings
    "sidebar": "sidebar-light-success",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,  # Allow expanding/collapsing
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False, 
    "sidebar_nav_flat_style": True,
    
    # Theme settings
    "theme": "default",
    "dark_mode_theme": None,
    
    # Button classes
    "button_classes": {
        "primary": "btn-outline-primary",
        "success": "btn-outline-success",
        "info": "btn-outline-info",
        "warning": "btn btn-warning",
        "danger": "btn-outline-danger",
        "secondary": "btn-outline-secondary"
    },
    
    # Other settings
    "actions_sticky_top": False,
    "use_google_fonts_cdn": True,
    "text_inputs": "form-control", 
    "select_inputs": "form-select"
}




ROOT_URLCONF = 'farm_management.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # "DIRS": [],
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'core.context_processors.sidebar_context',
                # 'core.context_processors.staff_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'farm_management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

RISPY_TEMPLATE_PACK = 'bootstrap4'



IMPORT_FORMATS = [CSV, JSON, XLS, XLSX]

# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
STORAGES = {
    'default': {
        'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
    },
    'staticfiles': {
        'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
    },
}

STORAGES = {
    'default': {
        'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

X_FRAME_OPTIONS = "SAMEORIGIN"
SILENCED_SYSTEM_CHECKS = ["security.W019"]

# Ensure Django finds your static files during development
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),  # Change this path if needed
]

# Only needed in production
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")  


LOGIN_REDIRECT_URL = "/home/"
LOGOUT_REDIRECT_URL = "/"
LOGIN_URL = 'login' 
